WebApplication2/WebApplication2/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Username required.", AllowEmptyStrings = false)]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password required.", AllowEmptyStrings = false)]
       [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

WebApplication2/WebApplication2/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class MyAccountController : Controller
    {
        // GET: MyAccount
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Login l, string ReturnUrl = "")
        {
            using (ChatbotDBEntities4 db = new ChatbotDBEntities4())
            {
                var user = db.Users.Where(a => a.Username.Equals(l.Username) && a.Password.Equals(l.Password)).FirstOrDefault();
                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(user.Username, l.RememberMe);
                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("MyProfile", "Home");
                    }
                }
            }
            ModelState.Remove("Password");
            return View();
        }




        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult EditProfile()
        {
            string username = User.Identity.Name;


            using (ChatbotDBEntities4 db = new ChatbotDBEntities4())
            {
                User user = db.Users.FirstOrDefault(u => u.Username.Equals(username));
                return View(user);
            }


        }

        [HttpPost]
        public ActionResult Edit(User u)
        {
            if (ModelState.IsValid)
            {
                ChatbotDBEntities4 db = new ChatbotDBEntities4();
                string username = User.Identity.Name;
                // Get the userprofile
                User user = db.Users.FirstOrDefault(a => u.Username.Equals(username));

                // Update fields
                user.FirstName = u.FirstName;
                user.LastName = u.LastName;
                user.Email = u.Email;
                user.Adress = u.Adress;
                user.Password = u.Password;
                user.Username = u.Username;

                db.Entry(user).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(u);
        }




    }
}

WebApplication2/WebApplication2/Views/MyAccount/EditProfile.cshtml
@model WebApplication2.User

@{
    ViewBag.Title = "EditProfile";
}

<h2>Edit Profile for User <b>@Model.Username </b></h2>


@using (Html.BeginForm("Edit", "MyAccount", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <p> Username :</p>@Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })<br>
    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
    <p> Password :</p> @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })<br>
    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    <p> First name:</p> @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } }) <br>
    <p> Last name:</p>@Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })<br>
    <p> E-mail:</p> @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })<br>
    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    <p> Address :</p>@Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })<br><br><br>

    <input type="submit" value="Submit" />
}

WebApplication2/WebApplication2/Views/MyAccount/Login.cshtml
@model WebApplication2.Models.Login

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RememberMe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RememberMe)
                    @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>